TRACK_LIBRARY = {
    "campus-food": {"name": "校园探店", "keywords": ["探店", "平价", "学生党", "真实测评"]},
    "study-tips": {"name": "学习分享", "keywords": ["考试周", "学习方法", "效率", "模板"]},
    "dorm-goodies": {"name": "宿舍好物", "keywords": ["宿舍", "平价", "好物", "收纳"]},
    "club-life": {"name": "社团生活", "keywords": ["社团", "活动", "幕后", "复盘"]},
    "food-local": {"name": "美食探店", "keywords": ["餐饮", "探店", "口碑", "性价比"]},
    "travel-city": {"name": "旅行城市", "keywords": ["城市攻略", "路线", "打卡", "避坑"]},
    "beauty-fashion": {"name": "美妆穿搭", "keywords": ["妆容", "穿搭", "测评", "风格"]},
    "fitness-health": {"name": "健身健康", "keywords": ["训练", "饮食", "身材管理", "习惯"]},
    "parenting-family": {"name": "母婴亲子", "keywords": ["育儿", "家庭", "亲子", "经验"]},
    "home-living": {"name": "家居生活", "keywords": ["装修", "收纳", "生活方式", "家居好物"]},
    "digital-tech": {"name": "数码科技", "keywords": ["手机", "AI工具", "软件", "效率"]},
    "career-work": {"name": "职场成长", "keywords": ["求职", "职场", "副业", "简历"]},
    "finance-business": {"name": "商业财经", "keywords": ["理财", "商业模式", "消费趋势", "案例"]},
    "knowledge-edu": {"name": "知识科普", "keywords": ["科普", "拆解", "方法论", "认知"]},
    "emotion-relationship": {"name": "情感关系", "keywords": ["亲密关系", "沟通", "情绪", "陪伴"]},
    "entertainment-pop": {"name": "娱乐热点", "keywords": ["热点", "影视", "明星", "二创"]},
    "game-anime": {"name": "游戏动漫", "keywords": ["游戏攻略", "二次元", "剧情", "测评"]},
    "pets": {"name": "宠物", "keywords": ["猫狗", "养宠", "萌宠", "用品"]},
    "car-mobility": {"name": "汽车出行", "keywords": ["新能源", "用车", "试驾", "出行"]},
    "local-life": {"name": "本地生活", "keywords": ["同城", "门店", "团购", "转化"]},
    "ecommerce-live": {"name": "电商带货", "keywords": ["选品", "种草", "直播", "转化"]},
    "brand-ip": {"name": "个人IP", "keywords": ["人设", "信任", "专业背书", "转粉"]},
    "vlog-daily": {"name": "Vlog日常", "keywords": ["生活记录", "陪伴感", "故事线", "真实感"]},
    "culture-art": {"name": "文化艺术", "keywords": ["艺术", "阅读", "展览", "审美"]},
    "custom-track": {"name": "其他/自定义赛道", "keywords": ["垂类", "细分人群", "内容定位", "差异化"]},
}

PLATFORM_LIBRARY = {
    "xiaohongshu": {"name": "小红书", "bias": "偏收藏、攻略、经验、避坑和清单表达"},
    "douyin": {"name": "抖音", "bias": "偏情绪钩子、冲突反差和短平快表达"},
    "bilibili": {"name": "B站", "bias": "偏信息密度、故事完整度和表达深度"},
    "kuaishou": {"name": "快手", "bias": "偏真实人设、信任关系、强互动和生活化表达"},
    "shipinhao": {"name": "视频号", "bias": "偏熟人传播、社交推荐、知识信任和私域转化"},
    "weibo": {"name": "微博", "bias": "偏热点话题、公共讨论、明星娱乐和实时传播"},
    "zhihu": {"name": "知乎", "bias": "偏专业解释、经验复盘、观点可信度和长尾搜索"},
    "wechat": {"name": "公众号/私域", "bias": "偏深度内容、信任沉淀、社群承接和转化链路"},
    "toutiao": {"name": "今日头条", "bias": "偏信息流推荐、标题效率、热点解读和下沉覆盖"},
    "baijiahao": {"name": "百家号", "bias": "偏搜索分发、资讯型内容和泛知识覆盖"},
    "douyin-live": {"name": "抖音直播/电商", "bias": "偏直播间转化、货品卖点、短视频引流和成交效率"},
    "taobao-content": {"name": "淘宝逛逛/淘宝内容", "bias": "偏种草到购买、商品场景、买家决策和转化"},
    "kuaishou-live": {"name": "快手直播/电商", "bias": "偏信任成交、老铁关系、实用卖点和复购"},
    "youtube": {"name": "YouTube", "bias": "偏长视频结构、搜索推荐、持续订阅和全球受众"},
    "tiktok": {"name": "TikTok", "bias": "偏强钩子、视觉节奏、趋势音乐和跨文化表达"},
    "instagram": {"name": "Instagram/Reels", "bias": "偏视觉审美、人设风格、生活方式和短视频种草"},
    "custom-platform": {"name": "其他/自定义平台", "bias": "需要结合用户补充的平台规则、目标人群和内容形态判断"},
}

STAGE_LIBRARY = {
    "cold-start": "冷启动期",
    "growth": "增长期",
    "conversion": "转化期",
}

